apiVersion: v1
kind: Service
metadata:
  name: dentsuaegistechtest-svc 
spec:
  selector:
    app: dentsuaegistechtest-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
